# Site settings
title: cookieluck
email: cc@cookieluck.ch
description: > # this means to ignore newlines until "baseurl:"
  you knowm just cookieluck and cc (corrupt <-> cookieluck)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cookieluck.ch" # the base hostname & protocol for your site
twitter_username: allevierminuten

# Build settings
markdown: kramdown
