# Site settings
title: cookieluck
email: gamecat@cookieluck.ch
description: > # this means to ignore newlines until "baseurl:"
  cookieluck log
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cookieluck.ch" # the base hostname & protocol for your site
twitter_username: allevierminuten

# Build settings
markdown: kramdown
